# Generated by Django 5.0.6 on 2024-08-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, max_length=400, null=True)),
                ('github_url', models.URLField(blank=True, max_length=400, null=True)),
                ('x_url', models.URLField(blank=True, max_length=400, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=70, null=True)),
                ('areas_of_expertise', models.TextField(blank=True, max_length=200, null=True)),
                ('professional_bio', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customeruser',
            name='bi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bi'),
        ),
    ]
