# Generated by Django 5.0.6 on 2024-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bi_customeruser_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
