# Generated by Django 5.0.6 on 2024-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_sequence_remove_resume_sequences_of_informations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='customer',
        ),
    ]
