# Generated by Django 5.0.6 on 2024-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicexperience',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='hardskill',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='opensourcecontribuition',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='professionalexperience',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='relevantproject',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='softskill',
            old_name='user',
            new_name='customer',
        ),
    ]
