# Generated by Django 5.0.6 on 2024-10-14 13:10

import apps.experiences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_rename_user_academicexperience_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardskill',
            name='skill_image',
            field=models.FileField(blank=True, null=True, upload_to='tecnologies_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='academicexperience',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='academicexperience',
            name='organization_logo',
            field=models.FileField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='instituition_logo',
            field=models.FileField(blank=True, null=True, upload_to='instituition_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='opensourcecontribuition',
            name='project_logo',
            field=models.FileField(blank=True, null=True, upload_to='project_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='organization_logo',
            field=models.FileField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='responsible_foto',
            field=models.FileField(blank=True, null=True, upload_to='responsible_fotos/', validators=[apps.experiences.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='relevantproject',
            name='project_logo',
            field=models.FileField(blank=True, null=True, upload_to='project_logos/', validators=[apps.experiences.models.validate_image_file]),
        ),
    ]
